-- View all data
-- Playstore Applications
SELECT *
FROM apps

-- App reviews
SELECT *
FROM reviews


-- Column information

EXEC sp_help 'apps'
EXEC sp_help 'reviews'


-- Change columns to suitable datatypes

-- Rating 
ALTER TABLE apps ALTER COLUMN Rating float;
--installs
ALTER TABLE apps ALTER COLUMN Installs float;
--Sentiment_Polarity
ALTER TABLE reviews ALTER COLUMN Sentiment_Polarity float;
--Sentiment_Subjectivity
ALTER TABLE reviews ALTER COLUMN Sentiment_Subjectivity float;

--                      *** QUERIES ***

-- 1. Which apps have the highest rating in the given available dataset?
SELECT App
FROM apps
WHERE rating = 5
ORDER BY Rating DESC



--2. What are the number of installs and reviews for the above apps? Return the apps with the highest reviews to the top.
SELECT	App,
		Installs,
		Reviews
FROM apps
WHERE rating = 5
ORDER BY Reviews DESC


--3. Which app has the highest number of reviews? Also, mention the number of reviews and category of the app
SELECT TOP(1)	App,
				category,
				Reviews
FROM apps	
ORDER BY Reviews DESC

--4. What is the total amount of revenue generated by the google play store by hosting apps? (Whenever a user buys apps  from the google play store, the amount is considered in the revenue)
SELECT	SUM(Price) as Total_revenue
FROM apps

--5. Which Category of google play store apps has the highest number of installs? also, find out the total number of installs for that particular category.
SELECT TOP (1)	category,
				SUM(installs) as Total_installs
FROM apps
GROUP BY category
ORDER BY SUM(installs) DESC

--6. Which Genre has the most number of published apps?
SELECT TOP(1)	genres,
				COUNT(*) as Published_apps
FROM apps
GROUP BY genres
ORDER BY Published_apps DESC
			



--7. Provide the list of all games ordered in such a way that the game that has the highest number of installs is displayed on the top
-- (to avoid duplicate results use distinct)
SELECT	DISTINCT(App),
		installs
FROM apps
WHERE category = 'game'
ORDER BY installs DESC


--8. Provide the list of apps that can work on android version 4.0.3 and UP.
SELECT DISTINCT(App)
FROM apps
WHERE Android_Ver = '4.0.3 and up'
ORDER BY APP

--9. How many apps from the given data set are free? Also, provide the number of paid apps.
SELECT	COUNT(*) as Total_free_apps,
		(SELECT COUNT(*) FROM apps WHERE Type = 'Paid')  as Total_apps

FROM apps
WHERE Type = 'Free'


--10. Which is the best dating app? (Best dating app is the one having the highest number of Reviews)
SELECT TOP (1) App
FROM apps
WHERE category = 'dating'
ORDER BY Reviews DESC


--11. Get the number of reviews having positive sentiment and number of reviews having negative sentiment for the app 10 best foods for you and compare them.
SELECT	Sentiment,
		COUNT(*) as Number_of_reviews
FROM reviews
WHERE App = '10 best foods for you' AND Sentiment != 'Neutral'
GROUP BY Sentiment
ORDER BY Number_of_reviews DESC

--12. Which comments of ASUS SuperNote have sentiment polarity and sentiment subjectivity both as 1?
SELECT Translated_Review
FROM reviews
WHERE App = 'ASUS SuperNote' AND CAST(sentiment_polarity as float) = 1 AND CAST(sentiment_subjectivity as float) = 1


--13. Get all the neutral sentiment reviews for the app Abs Training-Burn belly fat 
SELECT Translated_Review
FROM reviews
WHERE App = 'Abs Training-Burn belly fat' AND sentiment = 'neutral'


--14. Extract all negative sentiment reviews for Adobe Acrobat Reader with their sentiment polarity and sentiment subjectivity

SELECT	Translated_Review, 
		sentiment_polarity, 
		sentiment_subjectivity
FROM reviews
WHERE App = 'Adobe Acrobat Reader' AND sentiment = 'negative'




